In [8]:
import torch

x = torch.randn(3, requires_grad = True)
print(x)

tensor([-1.2720, -0.8093, -0.9218], requires_grad=True)


In [9]:
y =  x + 2
print(y) 

tensor([0.7280, 1.1907, 1.0782], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
print(z)

tensor([1.0598, 2.8356, 2.3251], grad_fn=<MulBackward0>)


In [11]:
z = z.mean()
print(z)

tensor(2.0735, grad_fn=<MeanBackward0>)


In [12]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9706, 1.5876, 1.4376])


In [15]:
# case 2
y = x+2
z = y*y*2
print(z)
v = torch.tensor([0.1, 0.1, 0.001], dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([1.0598, 2.8356, 2.3251], grad_fn=<MulBackward0>)
tensor([1.5530, 2.5402, 1.4462])


In [18]:
#  x.requires_grad_(False)
# x.detach()
# with torch.no_grad()
# Three ways to stop gradient function to get attached with the tensor variable
x.requires_grad_(False) # trialing underscore in pytorch means the variable will be modified inplace
print(x)
y = x.detach()
print(y)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([-1.2720, -0.8093, -0.9218])
tensor([-1.2720, -0.8093, -0.9218])
tensor([0.7280, 1.1907, 1.0782])


In [40]:
weights = torch.ones(4, requires_grad = True)

In [41]:
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])
tensor([3., 3., 3., 3.])
tensor([0., 0., 0., 0.])


In [31]:
# Lesson learnt: whenever specifying gradient, requires_grad param must be set to True

tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


tensor([9., 9., 9., 9.])
