In [1]:
# import libraries
import torch

In [9]:
x = torch.rand(2,2)
print(x)

tensor([[0.5633, 0.5665],
        [0.4651, 0.8566]])


In [8]:
x = torch.empty(2,2,3)
print(x)

tensor([[[1.1966e-35, 0.0000e+00, 1.5975e-43],
         [1.3873e-43, 1.4574e-43, 6.4460e-44]],

        [[1.4153e-43, 1.5274e-43, 1.5695e-43],
         [1.6255e-43, 1.6956e-43, 0.0000e+00]]])


In [10]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [15]:
x = torch.ones(2,2, dtype= torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [16]:
print(x.size())

torch.Size([2, 2])


In [17]:
x = torch.tensor([2.5, 0.1, ])
print(x)

tensor([2.5000, 0.1000])


In [18]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.9013, 0.6742],
        [0.2007, 0.0179]])
tensor([[0.1728, 0.1779],
        [0.5671, 0.8012]])


In [19]:
#addition
z = x + y
z = torch.add(x,y)
print(z)

tensor([[1.0741, 0.8521],
        [0.7678, 0.8191]])


In [20]:
y.add_(x)
print(y)

tensor([[1.0741, 0.8521],
        [0.7678, 0.8191]])


In [21]:
z = x - y
z = torch.sub(x,y)
print(z)

tensor([[-0.1728, -0.1779],
        [-0.5671, -0.8012]])


In [24]:
z1, z2, z3 = x * y, torch.mul(x,y), x.mul_(y)
print(z1, z2, z3)

tensor([[0.9681, 0.5745],
        [0.1541, 0.0147]]) tensor([[0.9681, 0.5745],
        [0.1541, 0.0147]]) tensor([[0.9681, 0.5745],
        [0.1541, 0.0147]])


In [25]:
z1 = x / y
print(z1)
z2 = torch.div(x,y)
print(z2)

tensor([[0.9013, 0.6742],
        [0.2007, 0.0179]])
tensor([[0.9013, 0.6742],
        [0.2007, 0.0179]])


In [26]:
x = torch.rand(5,3)
print(x)

tensor([[0.4336, 0.3981, 0.3765],
        [0.5475, 0.9117, 0.8471],
        [0.8701, 0.2865, 0.2507],
        [0.1675, 0.1576, 0.7150],
        [0.6847, 0.0385, 0.0096]])


In [28]:
print(x[:, 0])

tensor([0.4336, 0.5475, 0.8701, 0.1675, 0.6847])


In [29]:
print(x[1, :])

tensor([0.5475, 0.9117, 0.8471])


In [31]:
print(x[1,1].item())

0.9116911292076111


In [34]:
# reshaping a tensor
x = torch.rand(4,4)
print(x)
y1 = x.view(16)
print(y)
y2 = x.view(-1,8)
print(y2)

tensor([[0.7660, 0.6580, 0.3040, 0.0219],
        [0.3425, 0.2022, 0.4509, 0.9501],
        [0.6643, 0.5939, 0.4000, 0.0229],
        [0.3593, 0.5343, 0.1422, 0.3934]])
tensor([0.4256, 0.6747, 0.4776, 0.1864, 0.0079, 0.2574, 0.0394, 0.2305, 0.7207,
        0.1477, 0.6350, 0.8093, 0.4953, 0.1285, 0.9819, 0.8529])
tensor([[0.7660, 0.6580, 0.3040, 0.0219, 0.3425, 0.2022, 0.4509, 0.9501],
        [0.6643, 0.5939, 0.4000, 0.0229, 0.3593, 0.5343, 0.1422, 0.3934]])


In [36]:
# convert numpy array to tensor
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b), print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


(None, None)

In [37]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [38]:
print(b)

[2. 2. 2. 2. 2.]


In [39]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [40]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
